# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-02-28 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50, unique=True)),
                ('upassword', models.CharField(max_length=255)),
                ('utoken', models.CharField(max_length=255)),
                ('uemail', models.CharField(max_length=50, unique=True)),
                ('uFirstTime', models.DateTimeField(auto_now=True)),
                ('uLastTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
